# backend:
#   name: test-repo
#   local_backend: true

# The GitHub backend settings are commented out for local testing
backend:
  name: github
  repo: jasperSpeicher/atlas-of-emotions-1 # IMPORTANT: Replace with your repo path
  branch:  data-source-refactor # Or whichever branch you want to commit to
  # site_domain: your-site-domain.com # Optional: if you have GitHub gateway configured

media_folder: "static/assets/uploads"
public_folder: "/assets/uploads"

i18n:
  structure: multiple_files
  locales: [en, es, fr, de, it, pt, uk]
  default_locale: en

collections:
  - name: "translations"
    label: "Translation Files"
    label_singular: "Translation File"
    description: "JSON files containing the translations for different languages."
    folder: "static/strings/langs" # Path relative to repo root
    extension: "json"
    format: "json" # Expects a root object in the JSON file
    create: true # Allow creating new language groups (slugs)
    i18n: true # Enables i18n for this collection
    summary: "All Strings"
    editor:
      preview: false
    fields:
      - label: "String Groups"
        name: "string_groups" # Matches the root key in your JSON
        widget: "list"
        i18n: true # The content within groups is translatable
        fields:
          - label: "Group Name (Optional)"
            name: "group_name"
            widget: "string"
            required: false
            i18n: "duplicate"
          - label: "Items"
            name: "items"
            widget: "list"
            i18n: true
            fields:
              - label: "Key"
                name: "key"
                widget: "string"
                i18n: "duplicate"
              - label: "Value"
                name: "value"
                widget: "text"
                i18n: true
                required: false

  - name: "secondary_content"
    label: "Secondary Page Content"
    label_singular: "Secondary Page Content Item"
    description: "Content for various secondary pages like About, Annex, Donate, etc."
    folder: "static/strings/langs"
    filter: {field: "slug", value: "secondaryData"}
    identifier_field: "slug"
    extension: "json"
    format: "json"
    create: false
    i18n: true
    fields:
      - { label: "Identifier", name: "slug", widget: "hidden", default: "secondaryData", i18n: "duplicate" }
      - label: "Annex Pages"
        name: "annex"
        widget: "object"
        i18n: true
        required: true
        fields:
          - label: "Scientific Basis"
            name: "scientific-basis"
            widget: "object"
            i18n: true
            required: true
            fields:
              - { label: "Title", name: "title", widget: "string", i18n: true, required: true }
              - { label: "Introduction", name: "desc", widget: "markdown", i18n: true, required: true }
              - { label: "Content Introduction", name: "contentIntro", widget: "markdown", i18n: true, required: true }
              - label: "Content Items"
                name: "content"
                widget: "list"
                i18n: true
                required: true
                fields:
                  - { label: "Name/Percentage", name: "name", widget: "string", i18n: "duplicate", required: true }
                  - { label: "Description", name: "desc", widget: "string", i18n: true, required: true }
                  - { label: "Formatting Hint", name: "formatting", widget: "string", i18n: "duplicate", required: false }
              - label: "Footer Paragraphs"
                name: "footer"
                widget: "list"
                i18n: true
                required: true
                field: { label: "Paragraph", name: "paragraph", widget: "markdown", i18n: true }
          - label: "Triggers Timeline"
            name: "triggers-timeline"
            widget: "object"
            i18n: true
            required: true
            fields:
              - { label: "Title", name: "title", widget: "string", i18n: true, required: true }
              - { label: "Description", name: "desc", widget: "markdown", i18n: true, required: false }
              - label: "Content Items"
                name: "content"
                widget: "list"
                i18n: true
                required: true
                fields:
                  - { label: "Name", name: "name", widget: "string", i18n: "duplicate", required: true }
                  - { label: "Description", name: "desc", widget: "markdown", i18n: true, required: true }
              - label: "Footer Paragraphs"
                name: "footer"
                widget: "list"
                i18n: true
                required: true
                field: { label: "Paragraph", name: "paragraph", widget: "markdown", i18n: true }
          - label: "Intrinsic or Intentional Actions"
            name: "intrinsic-or-intentional"
            widget: "object"
            i18n: true
            required: true
            fields:
              - { label: "Title", name: "title", widget: "string", i18n: true, required: true }
              - { label: "Description", name: "desc", widget: "markdown", i18n: true, required: true }
              - label: "Emotions"
                name: "emotions"
                widget: "list"
                i18n: true
                required: true
                fields:
                  - { label: "Emotion Name", name: "name", widget: "string", i18n: "duplicate", required: true }
                  - label: "Action Types (Children)"
                    name: "children"
                    widget: "list"
                    i18n: true
                    required: true
                    fields:
                      - { label: "Type Name (e.g., Intrinsic)", name: "name", widget: "string", i18n: "duplicate", required: true }
                      - { label: "Type Description", name: "desc", widget: "markdown", i18n: true, required: true }
          - label: "Partially Charted Emotions"
            name: "partially-charted"
            widget: "object"
            i18n: true
            required: true
            fields:
              - { label: "Title", name: "title", widget: "string", i18n: true, required: true }
              - { label: "Description", name: "desc", widget: "markdown", i18n: true, required: true }
              - label: "Emotions"
                name: "emotions"
                widget: "list"
                i18n: true
                required: true
                fields:
                  - { label: "Emotion Name", name: "name", widget: "string", i18n: "duplicate", required: true }
                  - { label: "Emotion Description", name: "desc", widget: "markdown", i18n: true, required: true }
          - label: "Personality Traits"
            name: "personality-trait"
            widget: "object"
            i18n: true
            required: true
            fields:
              - { label: "Title", name: "title", widget: "string", i18n: true, required: true }
              - { label: "Description", name: "desc", widget: "markdown", i18n: true, required: true }
              - label: "Emotions"
                name: "emotions"
                widget: "list"
                i18n: true
                required: true
                fields:
                  - { label: "Emotion Name", name: "name", widget: "string", i18n: "duplicate", required: true }
                  - { label: "Trait Description", name: "desc", widget: "markdown", i18n: true, required: true }
          - label: "Moods"
            name: "moods"
            widget: "object"
            i18n: true
            required: true
            fields:
              - { label: "Title", name: "title", widget: "string", i18n: true, required: true }
              - { label: "Description", name: "desc", widget: "markdown", i18n: true, required: true }
              - label: "Moods List"
                name: "emotions"
                widget: "list"
                i18n: true
                required: true
                fields:
                  - { label: "Mood Name", name: "name", widget: "string", i18n: "duplicate", required: true }
                  - { label: "Mood Description", name: "desc", widget: "markdown", i18n: true, required: true }
          - label: "Psychopathology"
            name: "psychopathology"
            widget: "object"
            i18n: true
            required: true
            fields:
              - { label: "Title", name: "title", widget: "string", i18n: true, required: true }
              - { label: "Overall Description", name: "desc", widget: "markdown", i18n: true, required: true }
              - label: "Emotion-Specific Pathologies"
                name: "emotions"
                widget: "list"
                i18n: true
                required: true
                fields:
                  - { label: "Emotion Name", name: "name", widget: "string", i18n: "duplicate", required: true }
                  - { label: "Emotion Pathology Description", name: "desc", widget: "markdown", i18n: true, required: true }
                  - label: "Specific Disorders (Children)"
                    name: "children"
                    widget: "list"
                    i18n: true
                    required: true
                    fields:
                      - { label: "Disorder Name", name: "name", widget: "string", i18n: "duplicate", required: true }
                      - { label: "Disorder Description", name: "desc", widget: "markdown", i18n: true, required: true }
          - label: "Signals and Messages"
            name: "signals"
            widget: "object"
            i18n: true
            required: true
            fields:
              - { label: "Title", name: "title", widget: "string", i18n: true, required: true }
              - { label: "Overall Description", name: "desc", widget: "markdown", i18n: true, required: true }
              - label: "Emotion-Specific Signals"
                name: "emotions"
                widget: "list"
                i18n: true
                required: true
                fields:
                  - { label: "Emotion Name", name: "name", widget: "string", i18n: "duplicate", required: true }
                  - { label: "Top Level Emotion Desc (Optional)", name: "desc", widget: "string", i18n: true, required: false }
                  - label: "Signal/Message Pair (Children)"
                    name: "children"
                    widget: "list"
                    i18n: true
                    required: true
                    fields:
                      - { label: "Type (Signal/Message)", name: "name", widget: "string", i18n: "duplicate", required: true }
                      - { label: "Description", name: "desc", widget: "markdown", i18n: true, required: true }
          - label: "Impediments and Antidotes"
            name: "impediment-antidote"
            widget: "object"
            i18n: true
            required: true
            fields:
              - { label: "Title", name: "title", widget: "string", i18n: true, required: true }
              - { label: "Overall Description", name: "desc", widget: "markdown", i18n: true, required: true }
              - label: "Emotion Groups"
                name: "emotions"
                widget: "list"
                i18n: true
                required: true
                fields:
                  - { label: "Group Name (e.g., Anger Antidotes)", name: "name", widget: "string", i18n: "duplicate", required: true }
                  - label: "Items (Children)"
                    name: "children"
                    widget: "list"
                    i18n: true
                    required: false
                    default: []
                    fields:
                      - { label: "Item Name", name: "name", widget: "string", i18n: "duplicate", required: false }
                      - { label: "Item Description", name: "desc", widget: "markdown", i18n: true, required: false }
      - label: "About This Atlas Page"
        name: "about"
        widget: "object"
        i18n: true
        required: true
        fields:
          - { label: "Page Title", name: "title", widget: "string", i18n: true, required: true }
          - { label: "Page Description", name: "desc", widget: "markdown", i18n: true, required: true }
          - label: "Subsections"
            name: "subsections"
            widget: "list"
            i18n: true
            required: true
            fields:
              - { label: "Subsection Title", name: "title", widget: "string", i18n: true, required: true }
              - { label: "Subsection Description", name: "desc", widget: "markdown", i18n: true, required: true }
      - label: "Donate Page Content"
        name: "donate"
        widget: "object"
        i18n: true
        required: true
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true, required: true }
          - { label: "Description", name: "desc", widget: "markdown", i18n: true, required: true }
          - { label: "Link URL", name: "link", widget: "string", i18n: "duplicate", required: true }
          - label: "Images (URLs)"
            name: "imgs"
            widget: "list"
            i18n: true
            required: false
            field: { label: "Image URL", name: "url", widget: "string", i18n: "duplicate" }
      - label: "Further Reading Page Content"
        name: "further-reading"
        widget: "object"
        i18n: true
        required: true
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true, required: true }
          - { label: "Description", name: "desc", widget: "markdown", i18n: true, required: true }
          - label: "Links"
            name: "links"
            widget: "list"
            i18n: true
            required: true
            fields:
              - { label: "Link URL", name: "link", widget: "string", i18n: "duplicate", required: true }
              - { label: "Link Description", name: "desc", widget: "string", i18n: true, required: true }
      - label: "EmoTrak Page Content"
        name: "emotrak"
        widget: "object"
        i18n: true
        required: true
        fields:
          - { label: "Page Title", name: "title", widget: "string", i18n: true, required: false }
          - { label: "Page Description", name: "desc", widget: "markdown", i18n: true, required: true }
          - label: "Subsections"
            name: "subsections"
            widget: "list"
            i18n: true
            required: true
            fields:
              - { label: "Subsection Title", name: "title", widget: "string", i18n: true, required: false }
              - { label: "Subsection Description", name: "desc", widget: "markdown", i18n: true, required: true }
              - { label: "Image Key (Optional)", name: "image", widget: "string", i18n: "duplicate", required: false }
              - { label: "Include Mail Link (Optional)", name: "mail", widget: "boolean", i18n: "duplicate", required: false, default: false }

# All other GitHub related backend settings have been removed or are ensured to be commented out.
# Ensure there are no other 'backend:' sections. 